# Generated by Django 4.1.13 on 2025-11-02 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticashop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('idReporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('ticketsAbiertos', models.IntegerField()),
                ('ticketsCerrados', models.IntegerField()),
                ('tiempoProResolucion', models.FloatField()),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='idTecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_asignados', to='ticashop_app.usuario'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to='ticashop_app.usuario'),
        ),
        migrations.CreateModel(
            name='Licitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('propuesta', models.TextField()),
                ('estado', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticashop_app.usuario')),
            ],
            options={
                'verbose_name': 'Licitacion',
                'verbose_name_plural': 'Licitaciones',
            },
        ),
    ]
