# Generated by Django 4.1.13 on 2025-12-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticashop_app', '0002_alter_comentario_options_comentario_fichatecnica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='telefono_cliente',
        ),
    ]
